title: "FireBench Project"
description: "FireBench is a Python library designed for the systematic benchmarking and inter-comparison of fire models."
theme: "just-the-docs"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wirc-sjsu.github.io/firebench" # the base hostname & protocol for your site

# Just the Docs settings
just_the_docs:
  favicon:
    href: "/favicon.ico"  # Path to your favicon
  logo:
    src: "/images/firebench_logo.png"

# Navigation
nav:
  - title: "Home"
    url: "/"
  - title: "Workflows"
    url: "/workflows/"
    children:
      - title: "Sensitivity"
        url: "/workflows/sensitivity/"
        children:
          - title: "ROS Sensitivity to Environmental Variables"
            url: "/workflows/sensitivity/ros_sensitivity/"

defaults:
  - scope:
      path: ""  # applies to all files
      type: "pages"
    values:
      scripts: "/assets/js/mathjax.js"