name: Linting with Pylint

on:
  push:
    branches: [ dev-actions ]

jobs:
  pylint:
    runs-on: ubuntu-latest
    permissions:
        contents: write  # Grant write permissions for the job

    strategy:
        matrix:
          python-version: ['3.10']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        uses: Silleellie/pylint-github-action@v2
        with:
          path: src/firebench
          rcfile: .pylintrc
          github_token: ${{ secrets.GITHUB_TOKEN }}
