name: Pylint score up-to-date

on:
  push:
    branches: [ main, dev-actions ]
  pull_request:
    branches: [ main ]

jobs:
  pylint:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run pylint and update badge
        run: python .github/actions/run_pylint.py

      - name: Run pylint and check badge
        run: python .github/actions/run_pylint.py --check
