name: Security Analysis

on:
  push:
    branches: [ main, develop, release ]
  pull_request:
    branches: [ main ]

jobs:
  bandit:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit
        run: bandit -r src/firebench --severity-level high --confidence-level high
